@baseUrl = http://localhost:3001/api/persons
# @baseUrl = https://backend-full-stack-open.onrender.com

# get all phonebook persons
GET {{baseUrl}} HTTP/1.1

###
# get a person if exist
GET {{baseUrl}}/5 HTTP/1.1

###
# delete a person if exist
DELETE {{baseUrl}}/2 HTTP/1.1

###
# get numbers of persons and date
GET {{baseUrl}}/info

###
# post a new person in phonebook
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "85858800444"
}

###
# Update a person in phonebook
PUT {{baseUrl}}/661ee91dbbec40f1d5042a40 HTTP/1.1
content-type: application/json

{
    "name": "Sample5",
    "number": "9908800444"
}