@baseUrl = http://localhost:3001

# get all phonebook persons
GET {{baseUrl}}/api/persons HTTP/1.1

###
# get a person if exist
GET {{baseUrl}}/api/persons/5 HTTP/1.1

###
# delete a person if exist
DELETE {{baseUrl}}/api/persons/2 HTTP/1.1

###
# get numbers of persons and date
GET {{baseUrl}}/info

###
# post a new person in phonebook
POST {{baseUrl}}/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "85858800444"
}