@baseUrl = http://localhost:3001/api/users
# @baseUrl = https://backend-full-stack-open.onrender.com

# get all phonebook persons
GET {{baseUrl}} HTTP/1.1

###
# get a person if exist
GET {{baseUrl}}/5 HTTP/1.1

###
# delete a person if exist
DELETE {{baseUrl}}/2 HTTP/1.1

###
# post a new person in phonebook
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
